name: reviewmusik
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^5.0.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  http: ^1.2.1
  intl: ^0.19.0
  path_provider: ^2.1.3
  sqflite: ^2.4.2
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - images/

# Configuration for automatic launcher icon generation
flutter_icons:
  android: true
  ios: true
  image_path: "images/logodepan.png"
  adaptive_icon_background: "#1E1E2E"
  adaptive_icon_foreground: "images/logodepan.png"
